/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {completeSignIn,installAuthenticatedFetch,signOut,type AuthenticatedUser} from "../../lib/auth";

type Draft={id:number;status:string;firstName?:string;middleNames?:string;lastName?:string;email?:string;mobile?:string;university?:string;currentYear?:string;roomNo?:string;requestedStatus?:string;createdBy:string;updatedAt:string;notes?:string;};
export default function StudentDraftReview(){
 const[user,setUser]=useState<AuthenticatedUser|null|undefined>(undefined),[drafts,setDrafts]=useState<Draft[]>([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState<number|null>(null);
 useEffect(()=>{const restore=installAuthenticatedFetch();completeSignIn().then(u=>{if(!u||u.role!=="Admin"){setUser(null);return}setUser(u)}).catch(()=>setUser(null));return restore},[]);
 const load=async()=>{const r=await fetch("/api/v1/student-drafts");const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load drafts");setDrafts((j.drafts||[]).filter((d:Draft)=>d.status==="SUBMITTED"))};
 useEffect(()=>{if(user)void load().catch(e=>setError(e instanceof Error?e.message:"Unable to load drafts"))},[user]);
 const continueRegistration=(d:Draft)=>{setBusy(d.id);setError("");window.location.assign("/?studentDraftId="+encodeURIComponent(String(d.id)))};
 if(user===undefined)return <main className="production-login-page"><p>Checking session…</p></main>;
 if(!user)return <main className="production-login-page"><div className="production-login-card"><div className="production-login-brand"><span className="brand-logo"/><p className="tag">THE PERK HAVEN</p><h1>Management access required</h1><p>Sign in to the Management Portal as Admin, then reopen this page.</p></div><Link className="primary production-signin" href="/">Open Management Portal</Link></div></main>;
 return <main className="warden-portal"><header className="warden-topbar"><div><span className="warden-logo"/><b>The Perk Haven · Management Review</b></div><div><span>{user.name||user.email}</span><button onClick={signOut}>Sign out</button></div></header><section className="warden-content"><div className="warden-title"><div><p className="tag">WARDEN SUBMISSIONS</p><h1>Student Records Pending Completion</h1><p>Review the Warden submission, then continue in the normal Resident Registration form. The registration number is assigned only when the completed form is saved.</p></div><Link className="primary" href="/">← Management Portal</Link></div>{message&&<p className="warden-ok">✓ {message}</p>}{error&&<p className="form-error">⚠ {error}</p>}<div className="management-draft-rows">{drafts.map(d=><article key={d.id}><div><b>{[d.firstName,d.middleNames,d.lastName].filter(Boolean).join(" ")||"Unnamed student"}</b><small>{d.email||"No email"} · {d.mobile||"No mobile"} · {d.university||"University not entered"} · Room {d.roomNo||"not entered"} · Status {d.requestedStatus||"Inactive"} · Entered by {d.createdBy}</small>{d.notes&&<p>{d.notes}</p>}</div><button className="primary" disabled={busy===d.id} onClick={()=>continueRegistration(d)}>{busy===d.id?"Opening…":"Create Student Record"}</button></article>)}{!drafts.length&&<article><div><b>No submitted student drafts</b><small>New Warden submissions will appear here.</small></div></article>}</div></section></main>
}