package com.perkhaven.agreement;
import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import com.perkhaven.common.audit.AuditService; import com.perkhaven.common.error.NotFoundException; import com.perkhaven.common.sequence.NumberSequenceRepository; import com.perkhaven.security.AuthorizationService; import com.perkhaven.student.StudentRepository; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.time.Instant; import java.util.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/agreements") public class AgreementController{
 private final AgreementRepository agreements;private final StudentRepository students;private final NumberSequenceRepository sequences;private final ObjectMapper json;private final AuditService audit;private final AuthorizationService authorization;
 public AgreementController(AgreementRepository a,StudentRepository s,NumberSequenceRepository n,ObjectMapper j,AuditService au,AuthorizationService az){agreements=a;students=s;sequences=n;json=j;audit=au;authorization=az;}
 @GetMapping @PreAuthorize("isAuthenticated()") @Transactional(readOnly=true) public Map<String,Object> list(Authentication principal){return Map.of("agreements",agreements.findAllByOrderByIssuedAtDesc().stream().filter(a->authorization.canAccessStudent(a.getStudent().getRegistrationNo(),principal)).map(Response::from).toList());}
 @PostMapping @PreAuthorize("hasRole('ADMIN')") @Transactional public Map<String,Object> prepare(@Valid @RequestBody Prepare request){var student=students.findByRegistrationNoIgnoreCase(request.registrationNo()).orElseThrow(()->new NotFoundException("Student not found."));var previous=agreements.findFirstByStudentRegistrationNoIgnoreCaseOrderByRevisionDesc(request.registrationNo());String no;int revision;if(previous.isPresent()){no=previous.get().getAgreementNo();revision=previous.get().getRevision()+1;}else{var seq=sequences.findForUpdate("AGREEMENT").orElseThrow();no="PH-A-%05d".formatted(seq.takeNextValue());revision=0;}var agreement=agreements.save(new Agreement(no,revision,student,request.agreementData().toString()));audit.record("ISSUE","AGREEMENT",no,"Rev."+String.format("%02d",revision));return Map.of("agreement",Response.from(agreement));}
 @PostMapping("/{id}/sign") @PreAuthorize("isAuthenticated()") @Transactional public Map<String,Object> sign(@PathVariable long id,@Valid @RequestBody Sign request,Authentication principal){if(!request.consent())throw new IllegalArgumentException("Electronic signature consent is required.");var a=agreements.findById(id).orElseThrow(()->new NotFoundException("Agreement not found."));if(!authorization.canAccessStudent(a.getStudent().getRegistrationNo(),principal))throw new AccessDeniedException("This agreement belongs to another student.");if("Signed".equals(a.getStatus()))return Map.of("agreement",Response.from(a));a.sign(request.signedName().trim());audit.record("SIGN","AGREEMENT",a.getAgreementNo(),a.getSignedName());return Map.of("agreement",Response.from(a));}
 public record Prepare(@NotBlank String registrationNo,@NotNull JsonNode agreementData){} public record Sign(@NotBlank String signedName,boolean consent){}
 public record Response(Long id,String agreementNo,int revision,String revisionLabel,String registrationNo,String studentName,String roomNo,String startDate,String agreementDataJson,String status,Instant issuedAt,String signedName,Instant signedAt){static Response from(Agreement a){var s=a.getStudent();return new Response(a.getId(),a.getAgreementNo(),a.getRevision(),"Rev."+String.format("%02d",a.getRevision()),s.getRegistrationNo(),(s.getFirstName()+" "+s.getLastName()).trim(),s.getRoom()==null?"":s.getRoom().getRoomNo(),s.getStartDate().toString(),a.getAgreementDataJson(),a.getStatus(),a.getIssuedAt(),a.getSignedName(),a.getSignedAt());}}
}
