CREATE TABLE agreements (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 agreement_no VARCHAR(40) NOT NULL, revision INTEGER NOT NULL DEFAULT 0,
 student_id BIGINT NOT NULL REFERENCES students(id), agreement_data_json TEXT NOT NULL,
 status VARCHAR(30) NOT NULL, issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
 signed_name VARCHAR(220), signed_at TIMESTAMP WITH TIME ZONE,
 CONSTRAINT uk_agreement_revision UNIQUE (agreement_no, revision)
);
CREATE INDEX idx_agreements_student ON agreements(student_id, created_at DESC);
INSERT INTO number_sequences(sequence_key, next_value, version) VALUES ('AGREEMENT', 1, 0);
