CREATE TABLE checkout_settlements (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
 settlement_no VARCHAR(40) NOT NULL UNIQUE,
 student_id BIGINT NOT NULL REFERENCES students(id), settlement_data_json TEXT NOT NULL,
 checkout_date DATE,
 issued_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_checkout_settlements_student ON checkout_settlements(student_id, issued_at DESC);
INSERT INTO number_sequences(sequence_key, next_value, version) VALUES ('CHECKOUT_SETTLEMENT', 1, 0);
