CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    username VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(160) NOT NULL,
    role VARCHAR(40) NOT NULL,
    subject_type VARCHAR(30),
    subject_reference VARCHAR(80),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE staff_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    staff_no VARCHAR(40) NOT NULL,
    permission_key VARCHAR(80) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_staff_permission UNIQUE (staff_no, permission_key)
);

CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    room_no VARCHAR(30) NOT NULL UNIQUE,
    room_type VARCHAR(80) NOT NULL,
    beds INTEGER NOT NULL,
    price NUMERIC(14,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_room_beds CHECK (beds > 0),
    CONSTRAINT ck_room_price CHECK (price >= 0)
);

CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    registration_no VARCHAR(40) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    id_no VARCHAR(80) NOT NULL,
    mobile VARCHAR(40) NOT NULL,
    whatsapp VARCHAR(40),
    email VARCHAR(255) NOT NULL UNIQUE,
    university VARCHAR(255),
    current_year VARCHAR(80),
    address VARCHAR(600) NOT NULL,
    registered_date DATE NOT NULL,
    start_date DATE NOT NULL,
    room_id BIGINT,
    monthly_rent NUMERIC(14,2) NOT NULL,
    deposit_payable NUMERIC(14,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    photo_key VARCHAR(255),
    photo_name VARCHAR(255),
    photo_content_type VARCHAR(120),
    photo_size BIGINT,
    CONSTRAINT fk_student_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT ck_student_money CHECK (monthly_rent >= 0 AND deposit_payable >= 0)
);

CREATE TABLE student_emergency_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    student_id BIGINT NOT NULL,
    contact_order INTEGER NOT NULL,
    contact_name VARCHAR(200) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    relationship VARCHAR(100) NOT NULL,
    address VARCHAR(600),
    CONSTRAINT fk_student_contact FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    CONSTRAINT uk_student_contact_order UNIQUE (student_id, contact_order)
);

CREATE TABLE staff_designations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR(120) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    staff_no VARCHAR(40) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    id_no VARCHAR(80) NOT NULL,
    mobile VARCHAR(40) NOT NULL,
    whatsapp VARCHAR(40),
    email VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(600) NOT NULL,
    designation_id BIGINT,
    monthly_salary NUMERIC(14,2) NOT NULL,
    account_holder_name VARCHAR(200),
    account_no VARCHAR(100),
    bank VARCHAR(160),
    bank_branch VARCHAR(160),
    registered_date DATE NOT NULL,
    start_date DATE NOT NULL,
    finish_date DATE,
    status VARCHAR(20) NOT NULL,
    photo_key VARCHAR(255),
    photo_name VARCHAR(255),
    photo_content_type VARCHAR(120),
    photo_size BIGINT,
    CONSTRAINT fk_staff_designation FOREIGN KEY (designation_id) REFERENCES staff_designations(id),
    CONSTRAINT ck_staff_salary CHECK (monthly_salary >= 0)
);

CREATE TABLE staff_emergency_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    staff_id BIGINT NOT NULL,
    contact_order INTEGER NOT NULL,
    contact_name VARCHAR(200) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    relationship VARCHAR(100) NOT NULL,
    address VARCHAR(600),
    CONSTRAINT fk_staff_contact FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE,
    CONSTRAINT uk_staff_contact_order UNIQUE (staff_id, contact_order)
);

CREATE TABLE shops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    shop_no VARCHAR(40) NOT NULL UNIQUE,
    standard_rent NUMERIC(14,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_shop_rent CHECK (standard_rent >= 0)
);

CREATE TABLE shop_tenants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    registration_no VARCHAR(40) NOT NULL UNIQUE,
    shop_id BIGINT NOT NULL,
    business_name VARCHAR(200) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    id_no VARCHAR(80) NOT NULL,
    mobile VARCHAR(40) NOT NULL,
    whatsapp VARCHAR(40),
    email VARCHAR(255) NOT NULL,
    address VARCHAR(600) NOT NULL,
    registered_date DATE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    monthly_rent NUMERIC(14,2) NOT NULL,
    deposit_payable NUMERIC(14,2) NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_tenant_shop FOREIGN KEY (shop_id) REFERENCES shops(id),
    CONSTRAINT ck_tenant_money CHECK (monthly_rent >= 0 AND deposit_payable >= 0)
);

CREATE TABLE shop_tenant_emergency_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    shop_tenant_id BIGINT NOT NULL,
    contact_order INTEGER NOT NULL,
    contact_name VARCHAR(200) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    relationship VARCHAR(100) NOT NULL,
    address VARCHAR(600),
    CONSTRAINT fk_tenant_contact FOREIGN KEY (shop_tenant_id) REFERENCES shop_tenants(id) ON DELETE CASCADE,
    CONSTRAINT uk_tenant_contact_order UNIQUE (shop_tenant_id, contact_order)
);

CREATE TABLE number_sequences (
    sequence_key VARCHAR(80) PRIMARY KEY,
    next_value BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor VARCHAR(100) NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_reference VARCHAR(120) NOT NULL,
    detail VARCHAR(1000)
);

CREATE INDEX ix_students_name ON students(last_name, first_name);
CREATE INDEX ix_students_status_room ON students(status, room_id);
CREATE INDEX ix_staff_name ON staff(last_name, first_name);
CREATE INDEX ix_staff_status ON staff(status);
CREATE INDEX ix_shop_tenants_status_shop ON shop_tenants(status, shop_id);
CREATE INDEX ix_audit_entity ON audit_events(entity_type, entity_reference, created_at);
