ALTER TABLE students ALTER COLUMN id_no DROP NOT NULL;
ALTER TABLE students ALTER COLUMN mobile DROP NOT NULL;
ALTER TABLE students ALTER COLUMN email DROP NOT NULL;
ALTER TABLE students ALTER COLUMN address DROP NOT NULL;
