CREATE TABLE payment_evidence_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    submission_id VARCHAR(40) NOT NULL UNIQUE,
    invoice_id BIGINT NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    paid_date DATE NOT NULL,
    settlement_method VARCHAR(30) NOT NULL,
    remarks VARCHAR(1000),
    evidence_key VARCHAR(500) NOT NULL,
    evidence_name VARCHAR(255) NOT NULL,
    evidence_content_type VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    review_note VARCHAR(1000),
    reviewed_by VARCHAR(255),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    linked_payment_id BIGINT UNIQUE,
    CONSTRAINT fk_payment_evidence_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_evidence_payment FOREIGN KEY (linked_payment_id) REFERENCES payments(id) ON DELETE SET NULL,
    CONSTRAINT ck_payment_evidence_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_evidence_status CHECK (status IN ('PENDING', 'PROCESSED', 'REJECTED'))
);

CREATE INDEX ix_payment_evidence_student_invoice ON payment_evidence_submissions(invoice_id, status, created_at);

INSERT INTO number_sequences (sequence_key, next_value, version)
SELECT 'PAYMENT_EVIDENCE', 1, 0
WHERE NOT EXISTS (SELECT 1 FROM number_sequences WHERE sequence_key = 'PAYMENT_EVIDENCE');
