CREATE TABLE student_profile_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    registration_no VARCHAR(40) NOT NULL REFERENCES students(registration_no) ON DELETE CASCADE,
    requested_by_email VARCHAR(255) NOT NULL,
    original_values_json TEXT NOT NULL,
    proposed_changes_json TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    admin_note VARCHAR(2000),
    reviewed_by VARCHAR(255),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    email_status VARCHAR(80) NOT NULL DEFAULT 'Not sent'
);

CREATE INDEX idx_student_profile_requests_registration
    ON student_profile_requests(registration_no, created_at DESC);
CREATE INDEX idx_student_profile_requests_status
    ON student_profile_requests(status, created_at DESC);
