CREATE TABLE student_checkout_notice_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    registration_no VARCHAR(40) NOT NULL REFERENCES students(registration_no) ON DELETE CASCADE,
    request_type VARCHAR(20) NOT NULL,
    notice_date DATE NOT NULL,
    requested_checkout_date DATE NOT NULL,
    approved_checkout_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    review_note VARCHAR(2000),
    reviewed_by VARCHAR(255),
    reviewed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_checkout_notice_requests_registration
    ON student_checkout_notice_requests(registration_no, created_at DESC);
CREATE INDEX idx_checkout_notice_requests_status
    ON student_checkout_notice_requests(status, created_at DESC);
