CREATE TABLE student_room_transfer_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    request_no VARCHAR(40),
    registration_no VARCHAR(40) NOT NULL REFERENCES students(registration_no) ON DELETE CASCADE,
    current_room_no VARCHAR(30) NOT NULL,
    requested_room_no VARCHAR(30) NOT NULL,
    requested_date DATE NOT NULL,
    intended_start_date DATE NOT NULL,
    room_availability_status VARCHAR(30) NOT NULL,
    earliest_available_date DATE,
    reason VARCHAR(2000),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    transfer_date DATE,
    original_deposit_amount NUMERIC(14,2) NOT NULL,
    revised_deposit_amount NUMERIC(14,2) NOT NULL,
    review_note VARCHAR(2000),
    reviewed_by VARCHAR(255),
    reviewed_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX uq_student_room_transfer_request_no
    ON student_room_transfer_requests(request_no)
    WHERE request_no IS NOT NULL;

CREATE INDEX idx_student_room_transfer_registration
    ON student_room_transfer_requests(registration_no, created_at DESC);

CREATE INDEX idx_student_room_transfer_status
    ON student_room_transfer_requests(status, created_at DESC);
