ALTER TABLE students ADD COLUMN middle_names VARCHAR(180);
ALTER TABLE students ADD COLUMN date_of_birth DATE;

CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    invoice_no VARCHAR(80) NOT NULL UNIQUE,
    billing_key VARCHAR(100) NOT NULL UNIQUE,
    student_id BIGINT NOT NULL,
    invoice_type VARCHAR(20) NOT NULL,
    billing_month DATE,
    base_amount NUMERIC(14,2) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    paid_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    revision_number INTEGER NOT NULL DEFAULT 0,
    remarks VARCHAR(1000),
    email_status VARCHAR(40) NOT NULL,
    reissued_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_invoice_student FOREIGN KEY (student_id) REFERENCES students(id),
    CONSTRAINT ck_invoice_amounts CHECK (base_amount >= 0 AND amount >= 0 AND paid_amount >= 0),
    CONSTRAINT ck_invoice_revision CHECK (revision_number >= 0),
    CONSTRAINT ck_invoice_month CHECK (
        (invoice_type = 'DEPOSIT' AND billing_month IS NULL) OR
        (invoice_type = 'RENT' AND billing_month IS NOT NULL)
    )
);

CREATE INDEX ix_invoice_student_status ON invoices(student_id, status);
CREATE INDEX ix_invoice_month_status ON invoices(billing_month, status);

CREATE TABLE billing_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    invoice_id BIGINT NOT NULL,
    adjustment_type VARCHAR(40) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    note VARCHAR(500),
    CONSTRAINT fk_adjustment_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,
    CONSTRAINT uk_invoice_adjustment_type UNIQUE (invoice_id, adjustment_type)
);

CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    invoice_id BIGINT NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    message_body VARCHAR(4000) NOT NULL,
    attachment_name VARCHAR(255) NOT NULL,
    attachment_data BYTEA NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000),
    sent_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_notification_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

CREATE INDEX ix_notification_delivery ON notification_outbox(status, created_at);
