CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    transaction_id VARCHAR(40) NOT NULL UNIQUE,
    invoice_id BIGINT NOT NULL,
    paid_amount NUMERIC(14,2) NOT NULL,
    paid_date DATE NOT NULL,
    settlement_method VARCHAR(30) NOT NULL,
    remarks VARCHAR(1000),
    evidence_key VARCHAR(500) NOT NULL,
    evidence_name VARCHAR(255) NOT NULL,
    evidence_content_type VARCHAR(100) NOT NULL,
    CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    CONSTRAINT ck_payment_amount CHECK (paid_amount > 0)
);

CREATE INDEX ix_payment_invoice_date ON payments(invoice_id, paid_date, id);
