CREATE TABLE bank_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    bank_transaction_id VARCHAR(40) NOT NULL UNIQUE,
    source_fingerprint VARCHAR(64) NOT NULL UNIQUE,
    transaction_date DATE NOT NULL,
    remarks VARCHAR(1000),
    cheque_no VARCHAR(80),
    branch_code VARCHAR(80),
    branch_name VARCHAR(200),
    currency VARCHAR(10) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    dr_cr VARCHAR(10) NOT NULL,
    account_balance NUMERIC(14,2) NOT NULL,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_bank_transaction_amount CHECK (amount >= 0)
);

CREATE TABLE reconciliation_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    bank_transaction_id BIGINT NOT NULL,
    source_type VARCHAR(40) NOT NULL,
    source_record_id BIGINT NOT NULL,
    source_transaction_id VARCHAR(80) NOT NULL,
    reconciled_amount NUMERIC(14,2) NOT NULL,
    CONSTRAINT fk_reconciliation_bank FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE CASCADE,
    CONSTRAINT uk_reconciliation_source UNIQUE (source_type, source_record_id),
    CONSTRAINT ck_reconciliation_amount CHECK (reconciled_amount > 0)
);

CREATE INDEX ix_bank_transaction_date ON bank_transactions(transaction_date, id);
CREATE INDEX ix_reconciliation_bank ON reconciliation_links(bank_transaction_id);

INSERT INTO number_sequences (sequence_key, next_value, version)
SELECT 'BANK_TRANSACTION', 1, 0
WHERE NOT EXISTS (SELECT 1 FROM number_sequences WHERE sequence_key = 'BANK_TRANSACTION');
