CREATE TABLE expense_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  main_category VARCHAR(100) NOT NULL, name VARCHAR(160) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uk_expense_category UNIQUE (main_category, name)
);
CREATE TABLE expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  transaction_id VARCHAR(40) NOT NULL UNIQUE, category_id BIGINT NOT NULL REFERENCES expense_categories(id),
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0), transaction_date DATE NOT NULL,
  person_paid_staff_no VARCHAR(40) NOT NULL, person_paid_name VARCHAR(220) NOT NULL,
  settling_method VARCHAR(30) NOT NULL, evidence_key VARCHAR(500) NOT NULL,
  evidence_name VARCHAR(255) NOT NULL, evidence_content_type VARCHAR(120) NOT NULL,
  remarks VARCHAR(500), approval_status VARCHAR(40) NOT NULL, approval_note VARCHAR(500), approved_at TIMESTAMP WITH TIME ZONE
);
CREATE TABLE petty_cash_deposits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  transaction_id VARCHAR(40) NOT NULL UNIQUE, transaction_date DATE NOT NULL,
  amount NUMERIC(14,2) NOT NULL CHECK (amount > 0), evidence_key VARCHAR(500) NOT NULL,
  evidence_name VARCHAR(255) NOT NULL, evidence_content_type VARCHAR(120) NOT NULL,
  approval_status VARCHAR(30) NOT NULL, approval_note VARCHAR(500), approved_at TIMESTAMP WITH TIME ZONE
);
INSERT INTO number_sequences(sequence_key, next_value, version) VALUES ('EXPENSE', 1, 0);
INSERT INTO number_sequences(sequence_key, next_value, version) VALUES ('PETTY_CASH_DEPOSIT', 1, 0);

