package com.perkhaven.expense;
import com.perkhaven.common.audit.AuditService; import com.perkhaven.common.error.NotFoundException; import com.perkhaven.common.sequence.NumberSequenceRepository; import com.perkhaven.reconciliation.ReconciliationLinkRepository; import com.perkhaven.storage.StorageService; import java.io.IOException; import java.math.BigDecimal; import java.time.*; import java.util.*; import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
@RestController @RequestMapping("/api/v1/petty-cash") public class PettyCashController{
 private final PettyCashDepositRepository deposits;private final NumberSequenceRepository sequences;private final StorageService storage;private final ReconciliationLinkRepository links;private final AuditService audit;
 public PettyCashController(PettyCashDepositRepository d,NumberSequenceRepository n,StorageService s,ReconciliationLinkRepository l,AuditService a){deposits=d;sequences=n;storage=s;links=l;audit=a;}
 @GetMapping @PreAuthorize("isAuthenticated()") public Map<String,Object> list(){return Map.of("deposits",deposits.findAllByOrderByTransactionDateDescIdDesc().stream().map(Response::from).toList());}
 @PostMapping(consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("isAuthenticated()") @Transactional public Map<String,Object> create(@RequestParam LocalDate transactionDate,@RequestParam BigDecimal amount,@RequestPart("evidence") MultipartFile evidence)throws IOException{if(evidence.isEmpty()||amount.signum()<=0)throw new IllegalArgumentException("Valid amount and evidence are required.");var f=storage.store("petty-cash-evidence",evidence);var seq=sequences.findForUpdate("PETTY_CASH_DEPOSIT").orElseThrow();var d=deposits.save(new PettyCashDeposit("PCD-%04d-%04d".formatted(transactionDate.getYear(),seq.takeNextValue()),transactionDate,amount,f.key(),f.originalName(),f.contentType()));audit.record("CREATE","PETTY_CASH_DEPOSIT",d.getTransactionId(),null);return Map.of("deposit",Response.from(d));}
 @PatchMapping @PreAuthorize("hasAnyRole('ADMIN','CHAIRMAN','MANAGING_DIRECTOR')") @Transactional public Map<String,Object> review(@RequestBody Review r){var d=deposits.findById(r.id()).orElseThrow(()->new NotFoundException("Deposit not found."));d.review(r.approvalStatus(),r.approvalNote());links.deleteBySourceTypeAndSourceRecordId("Petty Cash Deposit",d.getId());return Map.of("deposit",Response.from(d));}
 @GetMapping("/evidence") @PreAuthorize("isAuthenticated()") public ResponseEntity<Resource> evidence(@RequestParam String transactionId){var d=deposits.findByTransactionId(transactionId).orElseThrow(()->new NotFoundException("Deposit not found."));return ResponseEntity.ok().contentType(MediaType.parseMediaType(d.getEvidenceContentType())).body(storage.load(d.getEvidenceKey()));}
 public record Review(Long id,String approvalStatus,String approvalNote,String role){} public record Response(Long id,String transactionId,LocalDate transactionDate,BigDecimal amount,String category,String evidenceName,String approvalStatus,String approvalNote,Instant approvedAt,Instant createdAt){static Response from(PettyCashDeposit d){return new Response(d.getId(),d.getTransactionId(),d.getTransactionDate(),d.getAmount(),"Petty Cash Deposit",d.getEvidenceName(),d.getApprovalStatus(),d.getApprovalNote(),d.getApprovedAt(),d.getCreatedAt());}}
}
