package com.perkhaven.shop;

import com.perkhaven.common.domain.*;import jakarta.persistence.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.ArrayList;import java.util.List;
@Entity @Table(name="shop_tenants")
public class ShopTenant extends AuditedEntity{
 @Column(name="registration_no",nullable=false,unique=true,length=40)private String registrationNo;@ManyToOne(fetch=FetchType.LAZY,optional=false)@JoinColumn(name="shop_id")private Shop shop;
 @Column(name="business_name",nullable=false,length=200)private String businessName;@Column(name="first_name",nullable=false,length=100)private String firstName;@Column(name="last_name",nullable=false,length=100)private String lastName;
 @Column(name="id_no",nullable=false,length=80)private String idNo;@Column(nullable=false,length=40)private String mobile;@Column(length=40)private String whatsapp;@Column(nullable=false)private String email;@Column(nullable=false,length=600)private String address;
 @Column(name="registered_date",nullable=false)private LocalDate registeredDate;@Column(name="start_date",nullable=false)private LocalDate startDate;@Column(name="end_date")private LocalDate endDate;
 @Column(name="monthly_rent",nullable=false,precision=14,scale=2)private BigDecimal monthlyRent;@Column(name="deposit_payable",nullable=false,precision=14,scale=2)private BigDecimal depositPayable;@Enumerated(EnumType.STRING)@Column(nullable=false,length=20)private RecordStatus status;
 @OneToMany(mappedBy="tenant",cascade=CascadeType.ALL,orphanRemoval=true)@OrderBy("order ASC")private List<ShopTenantEmergencyContact> emergencyContacts=new ArrayList<>();
 protected ShopTenant(){}public ShopTenant(String registrationNo){this.registrationNo=registrationNo;}public void update(Data d,Shop shop){this.shop=shop;businessName=d.businessName();firstName=d.firstName();lastName=d.lastName();idNo=d.idNo();mobile=d.mobile();whatsapp=d.whatsapp();email=d.email();address=d.address();registeredDate=d.registeredDate();startDate=d.startDate();endDate=d.endDate();monthlyRent=d.monthlyRent();depositPayable=d.depositPayable();status=d.status();emergencyContacts.clear();if(d.emergencyContacts()!=null)for(int i=0;i<d.emergencyContacts().size();i++){var c=d.emergencyContacts().get(i);emergencyContacts.add(new ShopTenantEmergencyContact(this,i+1,c.name(),c.phone(),c.relationship(),c.address()));}}
 public String getRegistrationNo(){return registrationNo;}public Shop getShop(){return shop;}public String getBusinessName(){return businessName;}public String getFirstName(){return firstName;}public String getLastName(){return lastName;}public String getIdNo(){return idNo;}public String getMobile(){return mobile;}public String getWhatsapp(){return whatsapp;}public String getEmail(){return email;}public String getAddress(){return address;}public LocalDate getRegisteredDate(){return registeredDate;}public LocalDate getStartDate(){return startDate;}public LocalDate getEndDate(){return endDate;}public BigDecimal getMonthlyRent(){return monthlyRent;}public BigDecimal getDepositPayable(){return depositPayable;}public RecordStatus getStatus(){return status;}public List<ShopTenantEmergencyContact>getEmergencyContacts(){return emergencyContacts;}
 public record Data(String businessName,String firstName,String lastName,String idNo,String mobile,String whatsapp,String email,String address,LocalDate registeredDate,LocalDate startDate,LocalDate endDate,BigDecimal monthlyRent,BigDecimal depositPayable,RecordStatus status,List<ContactData> emergencyContacts){}public record ContactData(String name,String phone,String relationship,String address){}
}
