package com.perkhaven.shop;

import com.perkhaven.common.api.PageResponse;import com.perkhaven.common.audit.AuditService;import com.perkhaven.common.domain.RecordStatus;import com.perkhaven.common.error.*;import jakarta.persistence.criteria.Predicate;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.LocalDate;import java.util.ArrayList;import java.util.List;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/shop-tenants")
public class ShopTenantController{
 private final ShopTenantRepository tenants;private final ShopRepository shops;private final AuditService audit;public ShopTenantController(ShopTenantRepository tenants,ShopRepository shops,AuditService audit){this.tenants=tenants;this.shops=shops;this.audit=audit;}
 @GetMapping @PreAuthorize("hasAnyRole('ADMIN','CHAIRMAN','MANAGING_DIRECTOR','WARDEN')") @Transactional(readOnly=true) public PageResponse<Response>list(@RequestParam(defaultValue="")String search,@RequestParam(required=false)RecordStatus status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="25")@Min(1)int size){Specification<ShopTenant>s=(r,q,b)->{var p=new ArrayList<Predicate>();if(!search.isBlank()){var t="%"+search.toLowerCase()+"%";p.add(b.or(b.like(b.lower(r.get("registrationNo")),t),b.like(b.lower(r.get("businessName")),t),b.like(b.lower(r.get("firstName")),t),b.like(b.lower(r.get("lastName")),t)));}if(status!=null)p.add(b.equal(r.get("status"),status));return b.and(p.toArray(Predicate[]::new));};return PageResponse.from(tenants.findAll(s,PageRequest.of(page,Math.min(size,100),Sort.by("registrationNo"))),Response::from);}
 @GetMapping("/{registrationNo}") @PreAuthorize("hasAnyRole('ADMIN','CHAIRMAN','MANAGING_DIRECTOR','WARDEN')") @Transactional(readOnly=true) public Response get(@PathVariable String registrationNo){return Response.from(find(registrationNo));}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @PreAuthorize("hasRole('ADMIN')") @Transactional public Response create(@Valid @RequestBody Request r){if(tenants.findByRegistrationNoIgnoreCase(r.registrationNo()).isPresent())throw new ConflictException("Registration number already exists.");var t=new ShopTenant(r.registrationNo());apply(t,r);tenants.save(t);audit.record("CREATE","SHOP_TENANT",t.getRegistrationNo(),null);return Response.from(t);}
 @PutMapping("/{registrationNo}") @PreAuthorize("hasRole('ADMIN')") @Transactional public Response update(@PathVariable String registrationNo,@Valid @RequestBody Request r){if(!registrationNo.equalsIgnoreCase(r.registrationNo()))throw new ConflictException("Registration number cannot be changed.");var t=find(registrationNo);apply(t,r);audit.record("UPDATE","SHOP_TENANT",registrationNo,null);return Response.from(t);}
 @DeleteMapping("/{registrationNo}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasRole('ADMIN')") @Transactional public void delete(@PathVariable String registrationNo){tenants.delete(find(registrationNo));audit.record("DELETE","SHOP_TENANT",registrationNo,null);}
 private void apply(ShopTenant t,Request r){var shop=shops.findByShopNoIgnoreCase(r.shopNo()).orElseThrow(()->new NotFoundException("Shop not found."));if(t.getShop()!=shop&&r.status()==RecordStatus.ACTIVE&&tenants.existsByShopIdAndStatus(shop.getId(),RecordStatus.ACTIVE))throw new ConflictException("Shop already has an active tenant.");var contacts=r.emergencyContacts()==null?List.<ShopTenant.ContactData>of():r.emergencyContacts().stream().map(c->new ShopTenant.ContactData(c.name(),c.phone(),c.relationship(),c.address())).toList();t.update(new ShopTenant.Data(r.businessName(),r.firstName(),r.lastName(),r.idNo(),r.mobile(),r.whatsapp(),r.email(),r.address(),r.registeredDate(),r.startDate(),r.endDate(),r.monthlyRent(),r.depositPayable(),r.status(),contacts),shop);}
 private ShopTenant find(String no){return tenants.findByRegistrationNoIgnoreCase(no).orElseThrow(()->new NotFoundException("Shop tenant not found."));}
 public record Request(@NotBlank String registrationNo,@NotBlank String shopNo,@NotBlank String businessName,@NotBlank String firstName,@NotBlank String lastName,@NotBlank String idNo,@NotBlank String mobile,String whatsapp,@Email @NotBlank String email,@NotBlank String address,@NotNull LocalDate registeredDate,@NotNull LocalDate startDate,LocalDate endDate,@NotNull @DecimalMin("0.00")BigDecimal monthlyRent,@NotNull @DecimalMin("0.00")BigDecimal depositPayable,@NotNull RecordStatus status,@Size(max=2)List<@Valid ContactRequest>emergencyContacts){}public record ContactRequest(@NotBlank String name,@NotBlank String phone,@NotBlank String relationship,String address){}public record ContactResponse(int order,String name,String phone,String relationship,String address){static ContactResponse from(ShopTenantEmergencyContact c){return new ContactResponse(c.getOrder(),c.getName(),c.getPhone(),c.getRelationship(),c.getAddress());}}
 public record Response(Long id,long version,String registrationNo,String shopNo,String businessName,String firstName,String lastName,String idNo,String mobile,String whatsapp,String email,String address,LocalDate registeredDate,LocalDate startDate,LocalDate endDate,BigDecimal monthlyRent,BigDecimal depositPayable,RecordStatus status,List<ContactResponse>emergencyContacts){static Response from(ShopTenant t){return new Response(t.getId(),t.getVersion(),t.getRegistrationNo(),t.getShop().getShopNo(),t.getBusinessName(),t.getFirstName(),t.getLastName(),t.getIdNo(),t.getMobile(),t.getWhatsapp(),t.getEmail(),t.getAddress(),t.getRegisteredDate(),t.getStartDate(),t.getEndDate(),t.getMonthlyRent(),t.getDepositPayable(),t.getStatus(),t.getEmergencyContacts().stream().map(ContactResponse::from).toList());}}
}
