spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: false
  flyway:
    locations: classpath:db/migration/common,classpath:db/migration/prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PERKHAVEN_SECURITY_COGNITO_ISSUER}

perkhaven:
  security:
    cognito:
      user-pool-id: ${PERKHAVEN_SECURITY_COGNITO_USER_POOL_ID:}
  storage:
    provider: ${STORAGE_PROVIDER:s3}
    bucket: ${PERKHAVEN_STORAGE_BUCKET}
